### ISSUE TITLE
Local state is not preserved as expected

### ISSUE THREAD

**Issue by dmotz** [rixo/svelte-template-hot#1]
I'm having trouble getting HMR working. Any save results in a full refresh and state loss for me.

Here's a basic example:
```svelte
<script>
  let n = 0
</script>

<main>
  <h1>{n}</h1>
  <button on:click={() => n++}>+</button>
</main>
```

Saving this component file results in `n` being reset to 0.

Any advice?

**Comment by rixo** [comment]
Full refresh like the page is fully reloaded, or do you have HMR partly working and just referring to the fact that local state is not preserved? (Local state is non exported `let` variables, like what you have here.)

**Comment by dmotz** [comment]
Ah yeah it looks to be a state reset via HMR reload. I didn't realize preserving local state was a limitation. Thanks for clarifying.

**Comment by rixo** [comment]
The limitation should be removed once [this](https://github.com/sveltejs/svelte/pull/3822) get merged.

The `next` branch of this template uses the next version of the HMR plugin, and a patched version of Svelte, with the aforementioned PR merged.

If you want to try it, I'm very interested in knowing if you consider that the behavior for local state and reactive statements (also affected in the current versions) is correct, according to your own expectations.

For example, with `degit`, you can:

~~~bash
npx degit rixo/svelte-template-hot#next my-app
~~~

Preserving local state is actually a pretty touchy endeavor, and I could use a second opinion on how it should actually work.

Also, preserving local state necessarily becomes annoying at times, typically when you've changed the init value of a variable but it won't be reflected because its value is preserved. With the `next` version, you can disable it during dev by writing `@!hmr` somewhere inside your component markup or a JS string `'@!hmr'` inside the `<script>` tag. (In the final cut it should be a comment, but this was faster to implement to test the idea.)

I'm changing the title of the issue, and reopening until local state is fixed. Maybe that'll help someone find the info.

**Comment by rixo** [comment]
Should now be fixed with last version of `rollup-plugin-svelte-hot` and Svelte >= 3.19.
