### ISSUE TITLE
Dynamic import?

### ISSUE THREAD

**Issue by mzaini30** [rixo/svelte-template-hot#15]
Can I using dynamic import for code splitting with this template?

**Comment by rixo** [comment]
Yes, absolutely. This is only a question of configuring Rollup. I wrote a [detailed answer](https://stackoverflow.com/a/60026703/1387519) on StackOverflow some time ago on how to do just that. There's also a [code-splitting branch](https://github.com/rixo/svelte-template-hot/tree/example-code-splitting) in this repo that is now badly outdated but it should give you an idea (relevant part of the config [here](https://github.com/rixo/svelte-template-hot/blob/0230d4f8f6f128fbe9bef50119d47e7432180458/rollup.config.js#L32)). I care to mention that Nollup also has full support for dynamic imports, so that's a no-compromise solution :) (To be completely honest, it might be a bit challenging to get just the right config to work both in Rollup & Nollup... Feel free to come back at me if you have a hard time figuring this, I'll help you sort it out.)

**Comment by mzaini30** [comment]
Thanks @rixo
